### PR TITLE
chore: improve ui for background map selector sheet

### PR DESCRIPTION
**Pull request by achou11**
~NOTE: this is stacked on #1049~ (now points to `develop`)

This PR attempts to update the map selector bottom sheet to be more visually aligned with the [design spec](https://www.figma.com/file/sxz2NvysPVab6ZTqs6f57K/Cobra-Collective?node-id=293%3A3081&t=gU5jBPUK0GG2eRNL-0)

image

### CODE REVIEW

**Review by ErikSin — APPROVED** [review]
Can you change the file name and component name of `BGMapSelector`, `BGMaps` (in experiments), and `BGMapCard`. Otherwise looks good to me!

**Comment by achou11** [comment]
> Can you change the file name and component name of `BGMapSelector`, `BGMaps` (in experiments), and `BGMapCard`. Otherwise looks good to me!

ah yes, thanks for the reminder!

**Comment by achou11** [comment]
@ErikSin is it okay to update the translation keys for these or should I keep them as is?

**Comment by ErikSin** [comment]
> @ErikSin is it okay to update the translation keys for these or should I keep them as is?

I think they are translated already, so leaving the key is probably best

**Pull request merged**
