### PR TITLE
chore: Remove REQUEST_INSTALL_PACKAGE permission

### PR DESCRIPTION
**Pull request by ErikSin**
Removed REQUEST_INSTALL_PACKAGE permission

### CODE REVIEW

**Review by achou11 — APPROVED** [review]
Just to confirm, we're okay with this feature not working for the non-Google Play builds for now? If so, we should create an issue to conditionally apply the permission based on build flavor, as something to work on in the future.

Relevant resources:
- https://stackoverflow.com/questions/28478110/android-studio-two-flavors-with-different-manifest-files/28480064#28480064
- https://developer.android.com/studio/build/manage-manifests#merge_rule_markers

**Comment by achou11** [comment]
Are there any documentation changes in this repo that need to be made as a result of this change?

**Comment by achou11** [comment]
also for extra context when looking back on this: Google Play isn't allowing us to publish a release with the permission in question due to policy stuff

**Comment by ErikSin** [comment]
> Just to confirm, we're okay with this feature not working for the non-Google Play builds for now? If so, we should create an issue to conditionally apply the permission based on build flavor, as something to work on in the future.
> 
> Relevant resources:
> 
>     * https://stackoverflow.com/questions/28478110/android-studio-two-flavors-with-different-manifest-files/28480064#28480064
> 
>     * https://developer.android.com/studio/build/manage-manifests#merge_rule_markers

I think we should. It does feel like quite a lot of work, so I don't want to do it now as we are mid sprint and we haven't decided if it is our priority. Ill mark it as something to consider next sprint and Ximena and I will discuss :)

**Comment by ErikSin** [comment]
> Are there any documentation changes in this repo that need to be made as a result of this change?

Yeah, actually ill wait to merge this until the programs team has approved of the copy that we are going to change in the app. I will also add it to `known problems` in our readme.

**Pull request merged**
