### PR TITLE
Add Mapeo-Web support

### PR DESCRIPTION
**Pull request by RangerMauve**
# Websync for mobile

This new feature will add the appropriate dependencies and the UI for websync. Users will be able to upload their observations to a dedicated server, and other people on the project will have the ability to sync with these uploaded observations.

### CODE REVIEW

**Comment by RangerMauve** [comment]
@gmaclennan Any idea why the e2e tests are failing? Is there something I can do about it?

**Comment by gmaclennan** [comment]
> @gmaclennan Any idea why the e2e tests are failing? Is there something I can do about it?

Let's see if https://github.com/digidem/mapeo-mobile/pull/505 fixes it. Also, however, I know Github is due to update their default container for Linux and do not include the same Android SDK components by default. If they have updated already, then we will need to fix that too most likely.

**Comment by gmaclennan** [comment]
ok #505 has fixed it. I've merged with master

**Comment by RangerMauve** [comment]
TODO: Rename: connectSync -> connectCloud

**Comment by RangerMauve** [comment]
Use existing hook config context, use context in the component

Don't encapsulate the URL within the usePeers hook, take it from the component

**Comment by gmaclennan** [comment]
woohoo the e2e tests pass :) (we don't test that much, so it's not that big an accomplishment!).
I want to run this through some tests on my own device first before we merge.

**Comment by gmaclennan** [comment]
@RangerMauve I've been testing this out today. I'll add issues as comments as I come across them, starting here:

**Bug Description**
Trying to sync with Mapeo Cloud when the project key is not activated shows spinning progress at 0%

**Expected behaviour**
The user should see an error state (existing sync targets have an error state when sync fails)

**Steps to reproduce**
1. Created a copy of `mapeo-default-settings` with a new random project key and `syncServer` set to `wss://cloud.mapeo.app`.
2. Did not add project key to Mapeo Cloud server
3. Loaded that config on the phone and pressed the sync button

**Comment by gmaclennan** [comment]
**Bug description**
After a failed sync, navigating away from the sync screen and then returning to it shows an additional cloud peer (see attached screenshot):

duplicate-peer-bug

**Expected behaviour**
Navigating away from the sync screen and returning to it should reset the error state and allow the user to try to sync again.

**Steps to reproduce**
1. Create a sync error (e.g. see steps in comment above)
2. Navigate away from the sync screen
3. Navigate back to the sync screen

**Comment by gmaclennan** [comment]
**Bug description**
Pressing sync with Mapeo Cloud just shows the indeterminate progress indicator, stuck at 0%, and stays there. However navigating to the observation sync screen shows that sync is actually complete.

**Expected behaviour**
Progress should be shown to the user during sync (progress indicator changes to determinate and % complete increases), and when sync is complete the "complete" state should show.

**Steps to reproduce**
1. Started with some existing observations on phone
2. Loaded config with syncServer configured
3. Synced with server
4. Fresh install of Mapeo Mobile (wipe local data)
5. Load same config that previously synced
6. Sync again with Mapeo Cloud - gets stuck. Observations do show in observations list.

This test was with project key starting with `039027`

**Comment by gmaclennan** [comment]
**Bug description**
App crashes several seconds after sync

crash-bug

**Expected behaviour**
No crashes!

**Steps to reproduce**
1. Follow steps in comment above
2. Sync
3. Wait

This seems to be caused by an uncaught error when the sync stream terminates, see logs:

```
02-08 15:45:53.755 21651 21772 E NODEJS-MOBILE: 2021-02-08T20:45:53.754Z mapeo-sync pump ended cloud.mapeo.app 443 undefined
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE: 2021-02-08T20:45:53.756Z mapeo-sync onClose cloud.mapeo.app 443 Error: sync stream terminated on remote side
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at /data/data/com.mapeo.debug/files/nodejs-project/index.js:75955:17
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at /data/data/com.mapeo.debug/files/nodejs-project/index.js:70976:7
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at f (/data/data/com.mapeo.debug/files/nodejs-project/index.js:57044:25)
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at Duplexify.<anonymous> (/data/data/com.mapeo.debug/files/nodejs-project/index.js:70934:5)
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at Duplexify.f (/data/data/com.mapeo.debug/files/nodejs-project/index.js:57044:25)
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at Duplexify.onfinish (/data/data/com.mapeo.debug/files/nodejs-project/index.js:57274:27)
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at Duplexify.emit (events.js:322:22)
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at Duplexify.EventEmitter.emit (domain.js:482:12)
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at finishMaybe (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55719:14)
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at afterWrite (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55581:3)
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at onwrite (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55572:7)
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at WritableState.onwrite (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55269:5)
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at onuncork (/data/data/com.mapeo.debug/files/nodejs-project/index.js:63271:8)
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at /data/data/com.mapeo.debug/files/nodejs-project/index.js:63479:7
02-08 15:45:53.766 21651 21772 E NODEJS-MOBILE:     at processTicksAndRejections (internal/process/task_queues.js:79:11)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE: 2021-02-08T20:45:53.766Z mapeo-sync emitting sync end/error event cloud.mapeo.app 443 Error: sync stream terminated on remote side
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at /data/data/com.mapeo.debug/files/nodejs-project/index.js:75955:17
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at /data/data/com.mapeo.debug/files/nodejs-project/index.js:70976:7
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at f (/data/data/com.mapeo.debug/files/nodejs-project/index.js:57044:25)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at Duplexify.<anonymous> (/data/data/com.mapeo.debug/files/nodejs-project/index.js:70934:5)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at Duplexify.f (/data/data/com.mapeo.debug/files/nodejs-project/index.js:57044:25)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at Duplexify.onfinish (/data/data/com.mapeo.debug/files/nodejs-project/index.js:57274:27)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at Duplexify.emit (events.js:322:22)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at Duplexify.EventEmitter.emit (domain.js:482:12)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at finishMaybe (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55719:14)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at afterWrite (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55581:3)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at onwrite (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55572:7)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at WritableState.onwrite (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55269:5)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at onuncork (/data/data/com.mapeo.debug/files/nodejs-project/index.js:63271:8)
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at /data/data/com.mapeo.debug/files/nodejs-project/index.js:63479:7
02-08 15:45:53.767 21651 21772 E NODEJS-MOBILE:     at processTicksAndRejections (internal/process/task_queues.js:79:11)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE: 2021-02-08T20:45:56.404Z mapeo-core:index uncaughtException Error: sync stream terminated on remote side
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at /data/data/com.mapeo.debug/files/nodejs-project/index.js:75955:17
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at /data/data/com.mapeo.debug/files/nodejs-project/index.js:70976:7
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at f (/data/data/com.mapeo.debug/files/nodejs-project/index.js:57044:25)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at Duplexify.<anonymous> (/data/data/com.mapeo.debug/files/nodejs-project/index.js:70934:5)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at Duplexify.f (/data/data/com.mapeo.debug/files/nodejs-project/index.js:57044:25)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at Duplexify.onfinish (/data/data/com.mapeo.debug/files/nodejs-project/index.js:57274:27)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at Duplexify.emit (events.js:322:22)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at Duplexify.EventEmitter.emit (domain.js:482:12)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at finishMaybe (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55719:14)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at afterWrite (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55581:3)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at onwrite (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55572:7)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at WritableState.onwrite (/data/data/com.mapeo.debug/files/nodejs-project/index.js:55269:5)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at onuncork (/data/data/com.mapeo.debug/files/nodejs-project/index.js:63271:8)
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at /data/data/com.mapeo.debug/files/nodejs-project/index.js:63479:7
02-08 15:45:56.405 21651 21772 E NODEJS-MOBILE:     at processTicksAndRejections (internal/process/task_queues.js:79:11)
02-08 15:45:56.407 21651 21772 E NODEJS-MOBILE: 2021-02-08T20:45:56.406Z mapeo-core:status state changed ERROR
02-08 15:45:56.408 21651 21772 E NODEJS-MOBILE: 2021-02-08T20:45:56.407Z mapeo-core:status sync stream terminated on remote side
02-08 15:45:56.532 21651 21722 I ReactNativeJS: 'mapeo:AppLoading status change +5m', 'ERROR'
```

**Comment by gmaclennan** [comment]
**Bug Description**
First sync does not complete. Observation list does not load. (this is similar to the bug above about sync not completing, but in that case I started with existing observations I had on my phone, where-as this case starts from a fresh install).
Stuck on 0%. Not clear if sync has completed or if there is an error.

**Steps to reproduce**
1. Fresh install of Mapeo
2. Created two observations, one with a photo
3. Created a new project key
4. Added project key to Mapeo cloud
5. Added config with project key to mapeo mobile
6. Tried to sync with Cloud
7. Stuck at 0%
8. Navigate to observation list and shows loading screen (observations that appeared before no longer appear).
9. Force quit app and restart
10. Observations now show.

I am not clear if anything actually synced with the server this time. The projectKey for this test starts with `c0c616`

**Comment by RangerMauve** [comment]
Regarding there not being errors when connecting to an instance is related to this code: https://github.com/digidem/mapeo-web/pull/4#discussion_r558459356

I don't have a good answer to this since it's hard to emit an error before the `handshake` event happens, and sadly that doesn't happen here since it closes early.

Would piping to an invalid `mapeo-core`instance on the `mapeo-web` side on invalid keys make sense? Then it'd follow the same error emitting semantics.

---

Regarding the error where it gets stuck at `0%` I haven't been able to reproduce it. Maybe I just don't have enough data to sync?

Here's what I get whenever I try to sync:

image

I only have one observation that I added manually by making up some coordinates since my emulator is having trouble providing fake GPS coordinates to the app.

Maybe you could DM me the key you used?

I'm also unable to reproduce the crashing error.

What version of Android were you using for this BTW? I was running this on an Android 10 emulator running on x86.

---

Regarding the error being thrown, I'm not entirely sure where the best place to listen for errors would be. I had assumed that passing the stream into mapeo-core would have set up all the necessary error handlers.

---

Regarding the invalid peer showing up in the peers list, I think this makes sense for when you've connected to a peer without doing a full handshake and getting the remote deviceType.

https://github.com/digidem/mapeo-mobile/blob/3bc482a3ad36caa93d043f63c470b9eaa505f139/src/frontend/screens/SyncModal/index.js#L61

The mapeo-mobile code expects the peer's deviceType to be set to `cloud` but since the connection never happens, it gets set to `websocket` since that's the default for websocket connections.

https://github.com/digidem/mapeo-core/blob/4f37aeb2bfc38e58a0e0ab272b921eeadc4303f4/sync.js#L96

We might want to make the default device type for websockets to be `cloud` to avoid this edge case?

**Comment by gmaclennan** [comment]
Duplicated entries in response from `mapeo-web list`

image

**Comment by RangerMauve** [comment]
Stuff to look into:

- Throw a 400 error in project replication WS before the WS handler actually parses it for invalid projects
- Add more logging to mapeo-web in the cloud to detect errors and stuff
- Figure out why connection isn't terminating gracefully on mapeo-mobile when actually syncing data
- Test if we can download observations / sync when we have new observations and observations we haven't loaded yet.

**Pull request closed without merging**
